update action

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -11,11 +11,25 @@ jobs:
       - uses: actions/checkout@v2
         with:
           ref: refs/pull/${{ github.event.pull_request.number }}/head
+      - name: Check pull request's name
+        run: |
+          prName = ${{ github.event.pull_request.title }}
+          university=`echo $prName | awk '{ sub(/.*\[/, ""); sub(/\].*/, ""); print }'`
+          echo university
+          universities=("SPBGU" "NUP" "CUB")
+          if [[ $(echo ${universities[@]} | grep -F -w $university) ]]
+          then 
+            echo "You are from $university !"
+            echo $university > university.txt
+          else 
+            echo "ERROR: Wrong university name or format in pull request title"
+            exit 1
+          fi
       - name: Check branches compatibility
         run: |
           if [ "${{ github.base_ref }}" != "${{ github.head_ref }}" ]; then
              echo "FIASCO: base and head branches differs"
-             exit 1
+      #  exit 1
           fi
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
@@ -46,14 +60,14 @@ jobs:
           docker exec -u root -t lama-testing-image chown -R opam:opam /home/opam/lama
           docker exec -u opam -w /home/opam/lama -t lama-testing-image sh -c 'eval $(opam config env) && make'
           echo "Regression: All checks have successfully passed"
-      - name: Check Deadline
-        run: |
-          deadline=2025-03-04T23:59
-          if [[ $(date +'%Y-%m-%d') > $deadline ]];
-          then
-              echo "FIASCO: The deadline has expired"
-              exit 1
-          fi
+      # - name: Check Deadline
+      #   run: |
+      #     deadline=2025-03-04T23:59
+      #     if [[ $(date +'%Y-%m-%d') > $deadline ]];
+      #     then
+      #         echo "FIASCO: The deadline has expired"
+      #         exit 1
+      #     fi
       - name: Prepare results
         run: |
           login=${{ github.event.pull_request.user.login }}
@@ -74,3 +88,4 @@ jobs:
             gitid.txt
             base.txt
             assignment_number.txt
+            university.txt
