upd

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -53,21 +53,20 @@ jobs:
       #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache
 
       - name: Retrieve Docker image
-        uses: actions/cache@v3
+        uses: actions/cache/restore@v3
         with:
           path: lama-1-30.tar
+          fail-on-cache-miss: true
           key: lama-1-30-${{ runner.os }}-
-          restore-keys: |
-            lama-1-30-${{ runner.os }}-
 
-      - name: Check if Lama-docker was restored from cache
-        run: |
-          if [ -f lama-1-30.tar ]; then
-            echo "Lama's docker image is restored successfully."
-          else
-            echo "Cache not found. Exiting..."
-            exit 1
-          fi
+      # - name: Check if Lama-docker was restored from cache
+      #   run: |
+      #     if [ -f lama-1-30.tar ]; then
+      #       echo "Lama's docker image is restored successfully."
+      #     else
+      #       echo "Cache not found. Exiting..."
+      #       exit 1
+      #     fi
 
       - name: Load image
         run: |
